In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import json

import warnings
warnings.filterwarnings("ignore")

print('numpy version - ', np.__version__)
print('pandas version - ', pd.__version__)

def seriesInfo(s):
    print('index - ', s.index, type(s.index))
    print('value - ', s.values, type(s.values))
    print()
    print('data - ')
    print(s)
    
def frmInfo(df):
    print('shape - ', df.shape)
    print('size - ', df.size)
    print('ndim - ', df.ndim)
    print('row index - ', df.index, type(df.index))
    print('col index - ', df.columns, type(df.columns))
    print('values - \n', df.values, type(df.values))
    print()
    print('data - ')
    display(df)

numpy version -  1.21.5
pandas version -  1.4.2

- 주유소 평균가격 확인
- 셀프 주유소는 정말 저렴할까?

[실습01]
지역으로 시작하는 모든 파일을 로드하고 병합

In [5]:
from glob import glob
print('glob(): 파일경로 등을 쉽게 접근할 수 있도록 도와주는 모듈의 함수')
stations_files = glob('./data/pandas_data/oil_data/지역*.xls')
stations_files

glob(): 파일경로 등을 쉽게 접근할 수 있도록 도와주는 모듈의 함수

['./data/pandas_data/oil_data\\지역_위치별(주유소) (1).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (10).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (11).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (12).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (13).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (14).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (15).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (16).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (17).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (18).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (19).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (2).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (20).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (21).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (22).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (23).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (24).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (3).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (4).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (5).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (6).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (7).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (8).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소) (9).xls',
 './data/pandas_data/oil_data\\지역_위치별(주유소).xls']

In [9]:
tmp_raw = []
for filePath in stations_files:
    tmp = pd.read_excel(filePath, header=2)
    tmp_raw.append(tmp)

In [10]:
# [실습02]
# 기본정보 확인 및 결측치 확인
stations_raw = pd.concat(tmp_raw)
stations_raw

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,서울특별시,오렌지주유소,서울 강동구 성안로 102 (성내동),SK에너지,02-484-6165,N,-,1554,1354,997
1,서울특별시,구천면주유소,서울 강동구 구천면로 357 (암사동),현대오일뱅크,02-441-0536,N,-,1556,1355,-
2,서울특별시,GS칼텍스㈜직영 신월주유소,서울 강동구 양재대로 1323 (성내동),GS칼텍스,02-475-2600,N,1855,1559,1349,1000
3,서울특별시,광성주유소,서울 강동구 올림픽로 673 (천호동),S-OIL,02-470-5133,N,-,1578,1388,1100
4,서울특별시,(주)소모에너지엔테크놀러지성내주유소,서울 강동구 올림픽로 578 (성내동),GS칼텍스,02-479-3838,Y,-,1588,1388,-
...,...,...,...,...,...,...,...,...,...,...
41,서울특별시,갤러리아주유소,서울 강남구 압구정로 426 (청담동),SK에너지,02-540-4965,N,2268,2059,1869,1206
42,서울특별시,동우주유소,서울특별시 강남구 봉은사로 311 (논현동),SK에너지,02-542-6726,N,2306,2105,1908,-
43,서울특별시,삼성주유소,서울 강남구 삼성로 521 (삼성동),SK에너지,02-538-0809,N,2305,2106,1909,1189
44,서울특별시,오천주유소,서울 강남구 봉은사로 503 (삼성동),SK에너지,02-545-2822,N,2293,2107,1909,1232
45,서울특별시,뉴서울(강남),서울 강남구 언주로 716 (논현동),SK에너지,02-518-5631,N,2420,2120,1920,1330

In [11]:
stations_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 537 entries, 0 to 45
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      537 non-null    object
 1   상호      537 non-null    object
 2   주소      537 non-null    object
 3   상표      537 non-null    object
 4   전화번호    537 non-null    object
 5   셀프여부    537 non-null    object
 6   고급휘발유   537 non-null    object
 7   휘발유     537 non-null    object
 8   경유      537 non-null    object
 9   실내등유    537 non-null    object
dtypes: object(10)
memory usage: 46.1+ KB

[실습03]
휘발유를 대상으로 분석 진행하기위해서 컬럼명 변경하여 서브셋 만들기

         상호,       주소,     휘발유, 셀프여부 , 상표
rename   oil_store , address , price , self_y_n , company

In [19]:
gasoline_frm = stations_raw.loc[:,['상호', '주소', '휘발유', '셀프여부', '상표']]
gasoline_frm.rename(columns = {'상호': 'oil_store', 
                                      '주소': 'address', 
                                      '휘발유': 'price', 
                                      '셀프여부': 'self_y_n',
                                      '상표': 'company'}, inplace = True)
gasoline_frm

              oil_store                    address price self_y_n company
0                오렌지주유소       서울 강동구 성안로 102 (성내동)  1554        N   SK에너지
1                구천면주유소      서울 강동구 구천면로 357 (암사동)  1556        N  현대오일뱅크
2        GS칼텍스㈜직영 신월주유소     서울 강동구 양재대로 1323 (성내동)  1559        N   GS칼텍스
3                 광성주유소      서울 강동구 올림픽로 673 (천호동)  1578        N   S-OIL
4   (주)소모에너지엔테크놀러지성내주유소      서울 강동구 올림픽로 578 (성내동)  1588        Y   GS칼텍스
..                  ...                        ...   ...      ...     ...
41              갤러리아주유소      서울 강남구 압구정로 426 (청담동)  2059        N   SK에너지
42                동우주유소  서울특별시 강남구  봉은사로 311 (논현동)  2105        N   SK에너지
43                삼성주유소       서울 강남구 삼성로 521 (삼성동)  2106        N   SK에너지
44                오천주유소      서울 강남구 봉은사로 503 (삼성동)  2107        N   SK에너지
45              뉴서울(강남)       서울 강남구 언주로 716 (논현동)  2120        N   SK에너지

[537 rows x 5 columns]

[실습04]
구별 주유소 가격을 조사하기 위해서 파생변수 생성(direct)
구별 정보확인
서울특별시 -> 성동구 대체
특별시 -> 도봉구 대체

In [48]:
# lst = []
# for address in gasoline_frm['address']:
#     lst.append(address.split()[1])
    
# or

gasoline_frm['direct'] = [address.split()[1] for address in gasoline_frm['address']]

In [49]:
gasoline_frm.head()

             oil_store                 address price self_y_n company direct
0               오렌지주유소    서울 강동구 성안로 102 (성내동)  1554        N   SK에너지    강동구
1               구천면주유소   서울 강동구 구천면로 357 (암사동)  1556        N  현대오일뱅크    강동구
2       GS칼텍스㈜직영 신월주유소  서울 강동구 양재대로 1323 (성내동)  1559        N   GS칼텍스    강동구
3                광성주유소   서울 강동구 올림픽로 673 (천호동)  1578        N   S-OIL    강동구
4  (주)소모에너지엔테크놀러지성내주유소   서울 강동구 올림픽로 578 (성내동)  1588        Y   GS칼텍스    강동구

In [50]:
gasoline_frm['direct'].unique()

array(['강동구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '서울특별시', '성북구',
       '송파구', '양천구', '영등포구', '강북구', '용산구', '은평구', '종로구', '중구', '중랑구',
       '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '특별시', '강남구'],
      dtype=object)

In [59]:
# 방법1
gasoline_frm.replace({'direct': '서울특별시'}, '성동구', inplace=True)
gasoline_frm.replace({'direct': '특별시'}, '도봉구', inplace=True)

In [62]:
# 방법2
gasoline_frm.loc[gasoline_frm['direct'] == '서울특별시', 'direct'] = '성동구'
gasoline_frm.loc[gasoline_frm['direct'] == '특별시', 'direct'] = '도봉구'

[실습05]
가격 정보 확인[ - 들어있음] 후
가격 정보가 기입되지 않은 주유소는 제거
컬럼 타입을 숫자형으로 변경
인덱스를 새롭게 정의(reset_index)
인덱스열을 제거

In [66]:
gasoline_frm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 537 entries, 0 to 45
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   oil_store  537 non-null    object
 1   address    537 non-null    object
 2   price      537 non-null    object
 3   self_y_n   537 non-null    object
 4   company    537 non-null    object
 5   direct     537 non-null    object
dtypes: object(6)
memory usage: 29.4+ KB

In [75]:
gasoline_frm.drop(list(gasoline_frm[gasoline_frm['price']=='-'].index) , axis = 0 , inplace=True)
gasoline_frm.reset_index(drop=True , inplace=True)
gasoline_frm['price'] = gasoline_frm['price'].astype(int)
gasoline_frm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 477 entries, 0 to 476
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   oil_store  477 non-null    object
 1   address    477 non-null    object
 2   price      477 non-null    int32
 3   self_y_n   477 non-null    object
 4   company    477 non-null    object
 5   direct     477 non-null    object
dtypes: int32(1), object(5)
memory usage: 20.6+ KB

[실습06]
구별 휘발유 평균가격 확인

In [78]:
gasoline_frm.groupby('direct').mean()

              price
direct
강남구     1798.357143
강동구     1649.437500
강북구     1534.333333
강서구     1571.129032
관악구     1603.687500
광진구     1565.750000
구로구     1595.526316
금천구     1578.000000
노원구     1597.857143
도봉구     1551.176471
동대문구    1573.315789
동작구     1549.833333
마포구     1679.083333
서대문구    1591.333333
서초구     1645.342105
성동구     1629.687500
성북구     1576.150000
송파구     1611.300000
양천구     1602.782609
영등포구    1656.566667
용산구     1923.571429
은평구     1538.562500
종로구     1941.777778
중구      1964.083333
중랑구     1535.375000

In [82]:
gasoline_pivot_frm = pd.pivot_table(gasoline_frm, index = 'direct', 
                                   values = 'price',
                                   aggfunc = np.mean)
gasoline_pivot_frm

              price
direct
강남구     1798.357143
강동구     1649.437500
강북구     1534.333333
강서구     1571.129032
관악구     1603.687500
광진구     1565.750000
구로구     1595.526316
금천구     1578.000000
노원구     1597.857143
도봉구     1551.176471
동대문구    1573.315789
동작구     1549.833333
마포구     1679.083333
서대문구    1591.333333
서초구     1645.342105
성동구     1629.687500
성북구     1576.150000
송파구     1611.300000
양천구     1602.782609
영등포구    1656.566667
용산구     1923.571429
은평구     1538.562500
종로구     1941.777778
중구      1964.083333
중랑구     1535.375000

[실습07]
서울지역 주유가격 상위 10, 하위 10 확인

In [85]:
price_top_10_frm = gasoline_frm.sort_values(by = 'price', ascending = False).head(10)
price_bottom_10_frm = gasoline_frm.sort_values(by = 'price', ascending = True).head(10)

In [86]:
price_top_10_frm

    oil_store                     address  price self_y_n company direct
293     서남주유소        서울 중구 통일로 30 (봉래동1가)   2132        N   SK에너지     중구
292     장충주유소      서울 중구 장충단로 202 (장충동1가)   2130        N   SK에너지     중구
111     양재주유소       서울 서초구 바우뫼로 178 (양재동)   2128        N   SK에너지    서초구
476   뉴서울(강남)        서울 강남구 언주로 716 (논현동)   2120        N   SK에너지    강남구
475     오천주유소       서울 강남구 봉은사로 503 (삼성동)   2107        N   SK에너지    강남구
291     통일주유소       서울 중구 동호로 296 (장충동2가)   2106        N   SK에너지     중구
256     청파주유소  서울특별시 용산구  청파로 311 (청파동1가)   2106        N   SK에너지    용산구
255    갈월동주유소   서울특별시 용산구  한강대로 322 (갈월동)   2106        N   SK에너지    용산구
474     삼성주유소        서울 강남구 삼성로 521 (삼성동)   2106        N   SK에너지    강남구
281     재동주유소     서울특별시 종로구  율곡로 58 (경운동)   2106        N   SK에너지    종로구

In [87]:
price_bottom_10_frm

          oil_store                     address  price self_y_n company direct
74         만남의광장주유소  서울 서초구 양재대로12길 73-71 (원지동)   1490        N  알뜰(ex)    서초구
310       강서오곡셀프주유소     서울특별시 강서구 벌말로 254 (오곡동)   1497        Y   SK에너지    강서구
404         태릉솔밭주유소      서울특별시 노원구 노원로 49 (공릉동)   1497        Y   S-OIL    노원구
231          수유동주유소    서울특별시 강북구  도봉로 395 (수유동)   1498        Y   GS칼텍스    강북구
201           도림주유소       서울 영등포구 도림로 343 (도림동)   1499        Y   알뜰주유소   영등포구
373          풀페이주유소      서울특별시 구로구 경인로 41 (온수동)   1499        N   SK에너지    구로구
203         (주)강서오일       서울 영등포구 도신로 151 (도림동)   1499        N  현대오일뱅크   영등포구
35            서경주유소        서울 동작구 대림로 46 (신대방동)   1499        N  현대오일뱅크    동작구
202  (주)대청에너지 대청주유소      서울 영등포구 가마산로 328 (대림동)   1499        N   GS칼텍스   영등포구
294         신일셀프주유소         서울 중랑구 상봉로 58 (망우동)   1499        Y   SK에너지    중랑구

In [88]:
print('각각의 프레임에 위도, 경도 추가 - googlemaps')
import googlemaps

각각의 프레임에 위도, 경도 추가 - googlemaps

In [89]:
gmaps = googlemaps.Client(key='AIzaSyDdki495w62u7ziBMaVuzyYf4n-VZ8tsGA')
gmaps

 API queries_quota: 60

In [99]:
lat = []
lng = []

for address in price_top_10_frm['address']:
    tmp_lst = gmaps.geocode(address, language = 'ko')
    lat.append(tmp_lst[0].get('geometry')['location']['lat'])
    lng.append(tmp_lst[0].get('geometry')['location']['lng'])

In [100]:
price_top_10_frm['lat'] = lat
price_top_10_frm['lng'] = lng

In [101]:
price_top_10_frm

,oil_store,address,price,self_y_n,company,direct,lat,lng
293,서남주유소,서울 중구 통일로 30 (봉래동1가),2132,N,SK에너지,중구,37.559112,126.972491
292,장충주유소,서울 중구 장충단로 202 (장충동1가),2130,N,SK에너지,중구,37.560803,127.007602
111,양재주유소,서울 서초구 바우뫼로 178 (양재동),2128,N,SK에너지,서초구,37.478071,127.039610
476,뉴서울(강남),서울 강남구 언주로 716 (논현동),2120,N,SK에너지,강남구,37.513530,127.031534
475,오천주유소,서울 강남구 봉은사로 503 (삼성동),2107,N,SK에너지,강남구,37.513458,127.053786
291,통일주유소,서울 중구 동호로 296 (장충동2가),2106,N,SK에너지,중구,37.560714,127.003177
256,청파주유소,서울특별시 용산구 청파로 311 (청파동1가),2106,N,SK에너지,용산구,37.548983,126.967087
255,갈월동주유소,서울특별시 용산구 한강대로 322 (갈월동),2106,N,SK에너지,용산구,37.546955,126.972218
474,삼성주유소,서울 강남구 삼성로 521 (삼성동),2106,N,SK에너지,강남구,37.513985,127.056521
281,재동주유소,서울특별시 종로구 율곡로 58 (경운동),2106,N,SK에너지,종로구,37.574357,126.987141

In [103]:
lat = []
lng = []

for address in price_bottom_10_frm['address']:
    tmp_lst = gmaps.geocode(address, language = 'ko')
    lat.append(tmp_lst[0].get('geometry')['location']['lat'])
    lng.append(tmp_lst[0].get('geometry')['location']['lng'])

In [104]:
price_bottom_10_frm['lat'] = lat
price_bottom_10_frm['lng'] = lng

In [105]:
price_bottom_10_frm

,oil_store,address,price,self_y_n,company,direct,lat,lng
74,만남의광장주유소,서울 서초구 양재대로12길 73-71 (원지동),1490,N,알뜰(ex),서초구,37.459906,127.042060
310,강서오곡셀프주유소,서울특별시 강서구 벌말로 254 (오곡동),1497,Y,SK에너지,강서구,37.555284,126.768567
404,태릉솔밭주유소,서울특별시 노원구 노원로 49 (공릉동),1497,Y,S-OIL,노원구,37.625918,127.085533
231,수유동주유소,서울특별시 강북구 도봉로 395 (수유동),1498,Y,GS칼텍스,강북구,37.642140,127.029568
201,도림주유소,서울 영등포구 도림로 343 (도림동),1499,Y,알뜰주유소,영등포구,37.507656,126.900191
373,풀페이주유소,서울특별시 구로구 경인로 41 (온수동),1499,N,SK에너지,구로구,37.489965,126.825487
203,(주)강서오일,서울 영등포구 도신로 151 (도림동),1499,N,현대오일뱅크,영등포구,37.506964,126.901468
35,서경주유소,서울 동작구 대림로 46 (신대방동),1499,N,현대오일뱅크,동작구,37.487947,126.908240
202,(주)대청에너지 대청주유소,서울 영등포구 가마산로 328 (대림동),1499,N,GS칼텍스,영등포구,37.498556,126.895791
294,신일셀프주유소,서울 중랑구 상봉로 58 (망우동),1499,Y,SK에너지,중랑구,37.590907,127.093834

In [108]:
price_top_10_frm.reset_index(inplace=True)
del price_top_10_frm['index']
price_top_10_frm

,oil_store,address,price,self_y_n,company,direct,lat,lng
0,서남주유소,서울 중구 통일로 30 (봉래동1가),2132,N,SK에너지,중구,37.559112,126.972491
1,장충주유소,서울 중구 장충단로 202 (장충동1가),2130,N,SK에너지,중구,37.560803,127.007602
2,양재주유소,서울 서초구 바우뫼로 178 (양재동),2128,N,SK에너지,서초구,37.478071,127.039610
3,뉴서울(강남),서울 강남구 언주로 716 (논현동),2120,N,SK에너지,강남구,37.513530,127.031534
4,오천주유소,서울 강남구 봉은사로 503 (삼성동),2107,N,SK에너지,강남구,37.513458,127.053786
5,통일주유소,서울 중구 동호로 296 (장충동2가),2106,N,SK에너지,중구,37.560714,127.003177
6,청파주유소,서울특별시 용산구 청파로 311 (청파동1가),2106,N,SK에너지,용산구,37.548983,126.967087
7,갈월동주유소,서울특별시 용산구 한강대로 322 (갈월동),2106,N,SK에너지,용산구,37.546955,126.972218
8,삼성주유소,서울 강남구 삼성로 521 (삼성동),2106,N,SK에너지,강남구,37.513985,127.056521
9,재동주유소,서울특별시 종로구 율곡로 58 (경운동),2106,N,SK에너지,종로구,37.574357,126.987141

In [106]:
import folium

In [109]:
map = folium.Map(location = [37.5202, 126.975])
map

In [110]:
for idx in price_top_10_frm.index : 
    folium.CircleMarker([price_top_10_frm['lat'][idx] , price_top_10_frm['lng'][idx]] , 
                        fill_color = 'red' , 
                        fill = True).add_to(map)
map